apiVersion: v1
data:
  github_token: Z2l0aHViX3BhdF8xMUEzRlRWTUEwbFoxbWoyR2dJa2trX1pydkNTalFIaE9NdnZWNVM2Yzc2Rm5sbVYyYnMzNmdCNGs2R3BWc0F1TXNSQUJUVkVLUVo5R05QcmNm
  email_password: U21hcnQxMjM0NTYh
kind: Secret
metadata:
  name: jmeter-creds
type: Opaque
